version: '3'

services:
  gem5_sim:
    image: gem5:${GEM5_VERSION:-v24.0.0.1}_${ISA:-X86}
    build:
      context: ./docker/gem5/
      dockerfile: ./Dockerfile
      args:
        - GEM5_VERSION=${GEM5_VERSION:-v24.0.0.1}
        - BUILD_ISA=${ISA:-X86}
        - ENABLE_DRAMSIM3=${ENABLE_DRAMSIM3:-1}
        - ENABLE_RAMULATOR=${ENABLE_RAMULATOR:-1}
    container_name: gem5_sim_container
    hostname: gem5_sim
    volumes:
      - ./work:/work
    tty: true
    stdin_open: true


  riscv_devel:
    image: riscv_devel:${RVTOOL_VERSION:-2023.10.12}
    build:
      context: ./docker/riscv_devel/
      dockerfile: ./Dockerfile
      args:
        - RELEASE_VERSION=${RVTOOL_VERSION:-2023.10.12}
    container_name: riscv_dev_container
    hostname: riscv_dev
    volumes:
      - ./work:/work
    tty: true
    stdin_open: true
    profiles: [riscv_devel]